[build]
  command = "npm run dev:client && npm run dev:server" # the command you run to build this file
  functions = "built-lambda" # netlify-lambda builds to this folder AND Netlify reads functions from here
  publish = "client" # create-react-app builds to this folder, Netlify should serve all these files statically